In [1]:
import numpy as np

In [4]:
arr = np.random.randint(10, 20, size=(6, 6))
arr

array([[13, 18, 12, 17, 18, 16],
       [11, 10, 13, 16, 10, 12],
       [15, 12, 12, 19, 10, 14],
       [12, 12, 17, 17, 12, 12],
       [18, 10, 16, 15, 17, 18],
       [11, 16, 16, 19, 10, 18]])

In [5]:
np.triu(arr)

array([[13, 18, 12, 17, 18, 16],
       [ 0, 10, 13, 16, 10, 12],
       [ 0,  0, 12, 19, 10, 14],
       [ 0,  0,  0, 17, 12, 12],
       [ 0,  0,  0,  0, 17, 18],
       [ 0,  0,  0,  0,  0, 18]])

In [6]:
np.tril(arr)

array([[13,  0,  0,  0,  0,  0],
       [11, 10,  0,  0,  0,  0],
       [15, 12, 12,  0,  0,  0],
       [12, 12, 17, 17,  0,  0],
       [18, 10, 16, 15, 17,  0],
       [11, 16, 16, 19, 10, 18]])

In [7]:
np.triu(arr, k=1)

array([[ 0, 18, 12, 17, 18, 16],
       [ 0,  0, 13, 16, 10, 12],
       [ 0,  0,  0, 19, 10, 14],
       [ 0,  0,  0,  0, 12, 12],
       [ 0,  0,  0,  0,  0, 18],
       [ 0,  0,  0,  0,  0,  0]])