## import : imports any python script or a module 
    1. it searches for it :
        - working directory / present directory
        - default environment locations / wherever python is installed 
    2. it interprets & attaches the entire script to the present kernel

In [1]:
import generic

Welcome


In [2]:
# use a variable or function of the imported file
generic.name

'Nimisha'

In [3]:
generic.subject

'Python'

In [4]:
generic.display()

Name = Nimisha Subject =  Python


In [5]:
pwd()

'/home/labsuser/Weekday_July_13'

In [ ]:
# to get list of all installed modules :
help('modules')

In [1]:
import math

In [2]:
print(dir(math))

['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [3]:
math.log(2)

0.6931471805599453

In [4]:
math.radians(90)

1.5707963267948966

In [5]:
help(math.radians)

Help on built-in function radians in module math:

radians(x, /)
    Convert angle x from degrees to radians.



In [6]:
?math.radians

Signature: math.radians(x, /)
Docstring: Convert angle x from degrees to radians.
Type:      builtin_function_or_method


In [7]:
math.radians 

<function math.radians(x, /)>

In [8]:
# alias 
m = math

In [9]:
m.radians(180)

3.141592653589793

In [10]:
math.radians(180)

3.141592653589793

In [11]:
# for second way i m deleting math & m as identifiers 
del(math)
del(m)

In [12]:
math.radians(90)

NameError: name 'math' is not defined

In [13]:
m.radians(90)

NameError: name 'm' is not defined

In [14]:
# importing using alias 
import math as m   

In [15]:
# math is not the identtifier
# m is the identifier for math

In [16]:
math.radians(90)

NameError: name 'math' is not defined

In [17]:
m.radians(90)

1.5707963267948966

In [18]:
# i want to use only sqrt from math

In [19]:
from math import sqrt

In [20]:
sqrt(44)

6.6332495807108

In [21]:
from math import sqrt,radians, asin

In [22]:
from math import * # import all the functions & cclasses of the module 
# while calling these now no need to menttion package name

In [23]:
log(2)

0.6931471805599453

# 1. NumPy : Numerical Python
        - arrays : creation & operations
        - random number generation
        - complex mathematical transformation laplace fouriers etc

## Arrays : Homogenous data structures whicch can store data in 1 or more dimensions 

In [24]:
# creation of 1 D array

In [26]:
import numpy as np

In [28]:
arr = np.array([23, 56, 89, 90, 32])
print('Array 1 : ',arr)
print('No. of Dimensions  :', arr.ndim)
print('Shape of the Array :', arr.shape)
print('Size of the  Array :', arr.size)
print('Dtypes of the array:', arr.dtype)

Array 1 :  [23 56 89 90 32]
No. of Dimensions  : 1
Shape of the Array : (5,)
Size of the array. : 5
Dtypes of the array: int64


In [29]:
print(dir(arr))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [30]:
arr2 = np.array([[23,65, 89, 88, 98],[43,33, 80, 45, 77],[67,82,9,100,32]])
print('Array 2 :\n',arr2)
print('No. of Dimensions  :', arr2.ndim)
print('Shape of the Array :', arr2.shape)
print('Size of the Array  :', arr2.size)
print('Dtypes of the Array:', arr2.dtype )

Array 2 :
 [[ 23  65  89  88  98]
 [ 43  33  80  45  77]
 [ 67  82   9 100  32]]
No. of Dimensions  : 2
Shape of the Array : (3, 5)
Size of the Array  : 15
Dtypes of the Array: int64


In [32]:
l = [[[23,65, 89, 88, 98],[43,33, 80, 45, 77],[67,82,9,100,32]]]
len(l)

1

In [33]:
arr = np.array([23,65, 89, 88, 98.0])
print('Array 1 : ',arr)
print('No. of Dimensions  :', arr.ndim)
print('Shape of the Array :', arr.shape)
print('Size of the array. :', arr.size)
print('Dtypes of the array:', arr.dtype )

Array 1 :  [23. 65. 89. 88. 98.]
No. of Dimensions  : 1
Shape of the Array : (5,)
Size of the array. : 5
Dtypes of the array: float64


In [34]:
arr = np.array([23,65, 89, 88, 98.0, '8809'])
print('Array 1 : ',arr)
print('No. of Dimensions  :', arr.ndim)
print('Shape of the Array :', arr.shape)
print('Size of the array. :', arr.size)
print('Dtypes of the array:', arr.dtype )

Array 1 :  ['23' '65' '89' '88' '98.0' '8809']
No. of Dimensions  : 1
Shape of the Array : (6,)
Size of the array. : 6
Dtypes of the array: <U32


In [35]:
arr = np.array([23,65, 89, 88, 98.0, '8809'], dtype = int)
print('Array 1 : ',arr)
print('No. of Dimensions  :', arr.ndim)
print('Shape of the Array :', arr.shape)
print('Size of the array. :', arr.size)
print('Dtypes of the array:', arr.dtype )

Array 1 :  [  23   65   89   88   98 8809]
No. of Dimensions  : 1
Shape of the Array : (6,)
Size of the array. : 6
Dtypes of the array: int64


In [38]:
arr = np.array([23,65, 89, 88, 98.0, '8809'], dtype = np.int32)
print('Array 1 : ',arr)
print('No. of Dimensions  :', arr.ndim)
print('Shape of the Array :', arr.shape)
print('Size of the array. :', arr.size)
print('Dtypes of the array:', arr.dtype )

Array 1 :  [  23   65   89   88   98 8809]
No. of Dimensions  : 1
Shape of the Array : (6,)
Size of the array. : 6
Dtypes of the array: int32


In [39]:
arr = np.array([23,65, 89, 88, 98.0, '88.09'], dtype = np.int32)
print('Array 1 : ',arr)
print('No. of Dimensions  :', arr.ndim)
print('Shape of the Array :', arr.shape)
print('Size of the array. :', arr.size)
print('Dtypes of the array:', arr.dtype )

ValueError: invalid literal for int() with base 10: '88.09'

In [40]:
arr = np.array([23,65, 89, 88, 98.0, '88.09'], dtype = np.float)
print('Array 1 : ',arr)
print('No. of Dimensions  :', arr.ndim)
print('Shape of the Array :', arr.shape)
print('Size of the array. :', arr.size)
print('Dtypes of the array:', arr.dtype )

Array 1 :  [23.   65.   89.   88.   98.   88.09]
No. of Dimensions  : 1
Shape of the Array : (6,)
Size of the array. : 6
Dtypes of the array: float64


In [41]:
arr = np.array([23,65, 89, 88, 98.0, '88.09a'], dtype = np.float)
print('Array 1 : ',arr)
print('No. of Dimensions  :', arr.ndim)
print('Shape of the Array :', arr.shape)
print('Size of the array. :', arr.size)
print('Dtypes of the array:', arr.dtype )

ValueError: could not convert string to float: '88.09a'

In [44]:
arr = np.array([23,65, 89, 88, 98.0, '88.09a', '' , 0, 0.0001, ' '], dtype = np.bool)
print('Array 1 : ',arr)
print('No. of Dimensions  :', arr.ndim)
print('Shape of the Array :', arr.shape)
print('Size of the array. :', arr.size)
print('Dtypes of the array:', arr.dtype )

Array 1 :  [ True  True  True  True  True  True False False  True  True]
No. of Dimensions  : 1
Shape of the Array : (10,)
Size of the array. : 10
Dtypes of the array: bool


In [46]:
arr2 = np.array([[23,65, 89, 88, 98],[43,33, 80, 45, 77],[67,82,9,100,32]])
print('Array 2 :\n',arr2)
print('No. of Dimensions  :', arr2.ndim)
print('Shape of the Array :', arr2.shape)
print('Size of the Array  :', arr2.size)
print('Dtypes of the Array:', arr2.dtype )

Array 2 :
 [[ 23  65  89  88  98]
 [ 43  33  80  45  77]
 [ 67  82   9 100  32]]
No. of Dimensions  : 2
Shape of the Array : (3, 5)
Size of the Array  : 15
Dtypes of the Array: int64


In [48]:
arr3 = np.array([[[23,65, 89, 88, 98],[43,33, 80, 45, 77],[67,82,9,100,32]]])
print('Array 3 :\n',arr3)
print('No. of Dimensions  :', arr3.ndim)
print('Shape of the Array :', arr3.shape)
print('Size of the Array  :', arr3.size)
print('Dtypes of the Array:', arr3.dtype )

Array 3 :
 [[[ 23  65  89  88  98]
  [ 43  33  80  45  77]
  [ 67  82   9 100  32]]]
No. of Dimensions  : 3
Shape of the Array : (1, 3, 5)
Size of the Array  : 15
Dtypes of the Array: int64


# random no generation

In [54]:
np.random.rand()  # 4 dimensional array

0.3892581977518683

In [55]:
np.random.rand(2)

array([0.68297456, 0.95533968])

In [56]:
np.random.rand(2,3)

array([[0.60497767, 0.73824997, 0.46892422],
       [0.84380572, 0.66730663, 0.36448518]])

In [57]:
np.random.rand(2,3,4)

array([[[0.1392976 , 0.77224049, 0.82580499, 0.75719766],
        [0.34146939, 0.29167295, 0.71959549, 0.47614567],
        [0.11785782, 0.24622334, 0.32607134, 0.23866816]],

       [[0.33306888, 0.5396492 , 0.86060425, 0.05562512],
        [0.19888228, 0.50186129, 0.16690775, 0.18270278],
        [0.60912996, 0.43900866, 0.07246589, 0.78462365]]])

In [62]:
np.random.randint(1, 100, (2,4))

array([[61, 88, 73, 79],
       [27, 95, 10, 22]])

In [68]:
# seed : fixes the randomness
np.random.seed(12)
arr_rand = np.random.randint(1, 100, (3,4))
print(arr_rand)

[[76 28  7  3]
 [ 4 68 77 49]
 [23 50 53  6]]


## other ways to ccreate arrays 

In [70]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [71]:
np.zeros((3,5), int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [72]:
np.zeros((3,5), str)

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [73]:
np.zeros((3,5), bool)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [75]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [76]:
np.ones((3,5), int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [77]:
np.ones((3,5), str)

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [78]:
np.ones((3,5), bool)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [79]:
np.zeros_like(arr_rand) # array of same shape & dtypes as the given array filled with 0

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [80]:
np.ones_like(arr_rand)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [81]:
np.eye(3,)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
np.eye(3,dtype =int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [84]:
np.eye(3,dtype =bool)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [94]:
np.random.seed(234)
arr_rand_2d = np.random.randint(1,200, (4,4))
print('Array :\n',arr_rand_2d )

Array :
 [[160  69 186  96]
 [162   4  55  64]
 [196  35  55 137]
 [ 93 122 168  86]]


In [87]:
# only diagonal :
np.diagonal(arr_rand_2d)

array([160,   4,  55,  86])

In [92]:
np.triu(arr_rand_2d)

array([[160,  69, 186,  96],
       [  0,   4,  55,  64],
       [  0,   0,  55, 137],
       [  0,   0,   0,  86]])

## Accesing data in array 

In [97]:
arr_rand_1d = np.random.randint(1,200, (10,))
print('Array :\n',arr_rand_1d )

Array :
 [106  46 174 132  78 112 124  74 180  20]


In [100]:
print(arr_rand_1d[0])
print(arr_rand_1d[1])

106
46


In [101]:
print(arr_rand_1d[-1])

20


In [102]:
print(arr_rand_1d[1:8])

[ 46 174 132  78 112 124  74]


In [103]:
arr_rand_2d

array([[160,  69, 186,  96],
       [162,   4,  55,  64],
       [196,  35,  55, 137],
       [ 93, 122, 168,  86]])

In [105]:
# for 2 dimensional
## arr_rand_2d[row(s), column(s)]
arr_rand_2d[2 , 1]

35

In [107]:
# one row
arr_rand_2d[ 0 ]

array([160,  69, 186,  96])

In [109]:
# one col 
arr_rand_2d[ : , 0 ]

array([160, 162, 196,  93])

In [110]:
# multiple rows 
arr_rand_2d[0:3]

array([[160,  69, 186,  96],
       [162,   4,  55,  64],
       [196,  35,  55, 137]])

In [ ]:
# only row from the data but still 2 dimension

In [111]:
arr_rand_2d[0:1, ]

array([[160,  69, 186,  96]])

In [113]:
arr_rand_2d

array([[160,  69, 186,  96],
       [162,   4,  55,  64],
       [196,  35,  55, 137],
       [ 93, 122, 168,  86]])

In [112]:
arr_rand_2d[:, 0:1 ]

array([[160],
       [162],
       [196],
       [ 93]])

In [ ]:
# arr3[sheet , row, column]

In [ ]:
# conditional accessing

In [116]:
# get all the scores > 100
arr_rand_2d > 100

array([[ True, False,  True, False],
       [ True, False, False, False],
       [ True, False, False,  True],
       [False,  True,  True, False]])

In [117]:
(arr_rand_2d > 100).all() # returns true only if all the values are true

False

In [118]:
(arr_rand_2d > 1).all()

True

In [119]:
(arr_rand_2d > 100).any() # returns true when even a single value is true 

True

In [120]:
(arr_rand_2d > 200).any()

False

In [122]:
arr_rand_2d > 100

array([[ True, False,  True, False],
       [ True, False, False, False],
       [ True, False, False,  True],
       [False,  True,  True, False]])

In [ ]:
0,0
0,2
1,0
2,0
2,3
3,1
3,2

In [121]:
np.where(arr_rand_2d > 100)

(array([0, 0, 1, 2, 2, 3, 3]), array([0, 2, 0, 0, 3, 1, 2]))

In [123]:
arr_rand_2d[arr_rand_2d > 100]

array([160, 186, 162, 196, 137, 122, 168])

In [124]:
arr_rand_2d[[0, 0 , 1, 2, 2, 3, 3],[0, 2, 0, 0, 3, 1,2 ]] # indices

array([160, 186, 162, 196, 137, 122, 168])

# Array Operations

In [125]:
arr_rand_2d.max()

196

In [126]:
arr_rand_2d.min()

4

### in 2 dimensional Array:
    - Axis = 0 Column wise operation | Row wise reduction
    - Axis = 1 Row Wise Operation | column wise reduction

In [128]:
arr_rand_2d

array([[160,  69, 186,  96],
       [162,   4,  55,  64],
       [196,  35,  55, 137],
       [ 93, 122, 168,  86]])

In [129]:
arr_rand_2d.max(axis = 0)

array([196, 122, 186, 137])

In [130]:
arr_rand_2d.max(axis = 1)

array([186, 162, 196, 168])

### in 3 dimensional array
    - Axis = 0  Matrix wise reduction
    - Axis = 1  Row wise reduction
    - Axis = 2  Column wise reduction

In [134]:
np.random.seed(987)
arr_rand_3d = np.random.randint(1,200, (3,4,5))
print('Array :\n',arr_rand_3d )

Array :
 [[[180  42  55  11 102]
  [155 132 173 147  63]
  [ 15 126  29 112 132]
  [144  68  65  27 183]]

 [[126 160  62  82 162]
  [ 90 108 127 155  79]
  [ 80 123  20 179 126]
  [ 35 139 188  68 118]]

 [[170   4 113 131 126]
  [175 166  35 111  36]
  [ 96  70 194 124 177]
  [ 46 194  89  20 134]]]


In [135]:
arr_rand_3d.max()

194

In [136]:
arr_rand_3d.shape
# 3 matrices
# 4 rows
# 5 columns

(3, 4, 5)

In [138]:
np.random.seed(365)
arr_rand_2d = np.random.randint(1,200, (4,5))
print('Array :\n',arr_rand_2d )
arr_rand_2d.shape

Array :
 [[ 83 181  34  92 173]
 [  6  74 155  57  37]
 [ 49  29 100  96   4]
 [168 128 168 127 172]]


(4, 5)

In [140]:
arr_rand_2d.shape[0] # no. of rows

4

In [141]:
arr_rand_2d.shape[1] # no. of columns

5

In [143]:
arr_rand_2d

array([[ 83, 181,  34,  92, 173],
       [  6,  74, 155,  57,  37],
       [ 49,  29, 100,  96,   4],
       [168, 128, 168, 127, 172]])

In [142]:
arr_rand_2d.max(axis = 0 )

array([168, 181, 168, 127, 173])

In [144]:
arr_rand_3d

array([[[180,  42,  55,  11, 102],
        [155, 132, 173, 147,  63],
        [ 15, 126,  29, 112, 132],
        [144,  68,  65,  27, 183]],

       [[126, 160,  62,  82, 162],
        [ 90, 108, 127, 155,  79],
        [ 80, 123,  20, 179, 126],
        [ 35, 139, 188,  68, 118]],

       [[170,   4, 113, 131, 126],
        [175, 166,  35, 111,  36],
        [ 96,  70, 194, 124, 177],
        [ 46, 194,  89,  20, 134]]])

In [146]:
arr_rand_3d.shape[0] # no. of matrices

3

In [147]:
arr_rand_3d.max(axis = 0)

array([[180, 160, 113, 131, 162],
       [175, 166, 173, 155,  79],
       [ 96, 126, 194, 179, 177],
       [144, 194, 188,  68, 183]])

In [148]:
arr_rand_3d.max(axis = 1) 

array([[180, 132, 173, 147, 183],
       [126, 160, 188, 179, 162],
       [175, 194, 194, 131, 177]])

In [149]:
arr_rand_3d.max(axis = 2) # column wise reduction 

array([[180, 173, 132, 183],
       [162, 155, 179, 188],
       [170, 175, 194, 194]])

In [ ]:
        [180,  42,  55,  11, 102],
        [155, 132, 173, 147,  63],
        [ 15, 126,  29, 112, 132],
        [144,  68,  65,  27, 183]
        
[180, 173, 132, 183]

In [151]:
arr_rand_2d

array([[ 83, 181,  34,  92, 173],
       [  6,  74, 155,  57,  37],
       [ 49,  29, 100,  96,   4],
       [168, 128, 168, 127, 172]])

In [153]:
arr_rand_2d.T

array([[ 83,   6,  49, 168],
       [181,  74,  29, 128],
       [ 34, 155, 100, 168],
       [ 92,  57,  96, 127],
       [173,  37,   4, 172]])

In [ ]:
# np.linalg.inv()

In [155]:
arr_rand_2d

array([[ 83, 181,  34,  92, 173],
       [  6,  74, 155,  57,  37],
       [ 49,  29, 100,  96,   4],
       [168, 128, 168, 127, 172]])

In [156]:
arr_rand_2d.flatten()

array([ 83, 181,  34,  92, 173,   6,  74, 155,  57,  37,  49,  29, 100,
        96,   4, 168, 128, 168, 127, 172])

In [154]:
arr_rand_2d.argmax() # index if array is 1d

1

In [157]:
arr_rand_2d.argmin()

14

In [158]:
# changing shape of an array

In [160]:
arr_rand_2d.shape

(4, 5)

In [161]:
arr_rand_2d.reshape((10,2)) # size should remain same

array([[ 83, 181],
       [ 34,  92],
       [173,   6],
       [ 74, 155],
       [ 57,  37],
       [ 49,  29],
       [100,  96],
       [  4, 168],
       [128, 168],
       [127, 172]])

In [164]:
print('Before :\n',arr_rand_2d, sep ='')
print('After :\n',arr_rand_2d.reshape((2,2,5)), sep = '')
print('after :\n',arr_rand_2d, sep ='')

Before :
[[ 83 181  34  92 173]
 [  6  74 155  57  37]
 [ 49  29 100  96   4]
 [168 128 168 127 172]]
After :
[[[ 83 181  34  92 173]
  [  6  74 155  57  37]]

 [[ 49  29 100  96   4]
  [168 128 168 127 172]]]
after :
[[ 83 181  34  92 173]
 [  6  74 155  57  37]
 [ 49  29 100  96   4]
 [168 128 168 127 172]]


In [165]:
print('Before :\n',arr_rand_2d, sep ='')
arr_rand_2d.shape = (2,2,5)

Before :
[[ 83 181  34  92 173]
 [  6  74 155  57  37]
 [ 49  29 100  96   4]
 [168 128 168 127 172]]


In [166]:
print('After :\n',arr_rand_2d, sep ='')

After :
[[[ 83 181  34  92 173]
  [  6  74 155  57  37]]

 [[ 49  29 100  96   4]
  [168 128 168 127 172]]]


In [ ]:
args Kwargs ?