In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
playstore = pd.read_csv('/Users/nimisha/Desktop/Purdue/Python/googleplaystore.csv')

In [8]:
playstore['App']

0           Photo Editor & Candy Camera & Grid & ScrapBook
1                                      Coloring book moana
2        U Launcher Lite – FREE Live Cool Themes, Hide ...
3                                    Sketch - Draw & Paint
4                    Pixel Draw - Number Art Coloring Book
                               ...                        
10836                                     Sya9a Maroc - FR
10837                     Fr. Mike Schmitz Audio Teachings
10838                               Parkinson Exercices FR
10839                        The SCP Foundation DB fr nn5n
10840        iHoroscope - 2018 Daily Horoscope & Astrology
Name: App, Length: 10841, dtype: object

In [17]:
np.random.seed(123)
nrows = playstore.shape[0]
rand_ind = np.random.choice(range(nrows), 10, replace = False)
rand_ind 

array([6603, 9050, 9701,   97, 6685, 2310, 3568, 6389,  298,  628])

# Confidene Interval

* Compute z1 & z2 for:
        - area on left  of z1 is 2.5%
        - area on right of z2 is 2.5%

In [18]:
import scipy.stats as stats
from math import sqrt

In [21]:
z1 = stats.norm.ppf(0.025, loc = 0, scale = 1)
z2 = stats.norm.ppf(1 - 0.025, loc = 0, scale = 1)

In [22]:
z1, z2

(-1.9599639845400545, 1.959963984540054)

        - The Wall Street Journal reported that automobile crashes cost the United States $162 billion annually (TheWall Street Journal, March 5, 2008). The average cost per person for crashes in the Tampa, Florida, area was reported to be $1599. Suppose this average cost was based on a sample of 50 persons who had been involved in car crashes and that the population standard deviation is σ = $600. What is the margin of error for a 95% confidence interval? What would you recommend if the study required a margin of error of $150 or less?

### margin of error = z (alpha/2) * sigma/sqrt(n)

In [25]:
xbar = 1599
sigma = 600
n = 50
c = 0.95
alpha = 1 - c
z = stats.norm.ppf(alpha/2)
z * sigma/ sqrt(n)
moe = z * sigma/ sqrt(n)

In [26]:
mu1 = xbar + moe
mu2 = xbar - moe

In [28]:
print('95% CI = {:.0f} - {:.0f}'.format(mu1,mu2))

95% CI = 1433 - 1765


In [29]:
'i have {} books and have read {} of them in {} days'.format(100, 10,2)

'i have 100 books and have read 10 of them in 2 days'

In [31]:
'the price of winning is {:.2f}. i want to win badly! '.format(3400273/57)

'the price of winning is 59653.91. i want to win badly! '

In [33]:
xbar = 1599
sigma = 600
n = [45, 50, 75]
c = 0.95
alpha = 1 - c
z = stats.norm.ppf(alpha/2)
for size in n: 
    moe = z * sigma/ sqrt(size)
    print('For sample size {} moe = {:.2f}'.format(size, abs(moe)))
    

For sample size 45 moe = 175.30
For sample size 50 moe = 166.31
For sample size 75 moe = 135.79


    - Nielsen Media Research conducted a study of household television viewing times during the 8 p.m. to 11 p.m. time period. The data contained in the file named Nielsen are consistent with the findings reported (The World Almanac, 2003). Based upon past studies the population standard deviation is assumed known with σ = 3.5 hours. Develop a 95% confidence interval estimate of the mean television viewing time per week during the 8 p.m. to 11 p.m. time period.


In [34]:
nielsen = pd.read_csv('~/Downloads/Nielsen.CSV')

## mu = xbar +/- z * sigma/sqrt(n)

In [41]:
# sample_mean 
xbar = nielsen.Hours.mean()
sigma = 3.5
n = nielsen.Hours.size
c = 0.95
alpha = 1 - c
z = stats.norm.ppf(alpha/2)
moe = z * sigma/ sqrt(n)
mu1 = xbar + moe
mu2 = xbar - moe
print('95% CI = {:.1f} - {:.1f}'.format(mu1,mu2))

95% CI = 8.1 - 8.9


## t distribution :

In [42]:
# assume sigma was unknown 
xbar = nielsen.Hours.mean()
s = nielsen.Hours.std()
n = nielsen.Hours.size
df = n-1
c = 0.95
alpha = 1 - c
t = stats.t.ppf(alpha/2, df)
moe = t * s/ sqrt(n)
mu1 = xbar + moe
mu2 = xbar - moe
print('95% CI = {:.1f} - {:.1f}'.format(mu1, mu2))

95% CI = 8.1 - 8.9


## direct function for confidenncce Interval

In [47]:
np.array(stats.norm.interval(0.95, loc = nielsen.Hours.mean(), scale  = 3.5/sqrt(nielsen.Hours.size))).round(1)

array([8.1, 8.9])

In [46]:
np.array(stats.t.interval(0.95,df = nielsen.Hours.size -1, 
                          loc = nielsen.Hours.mean(), 
                          scale  =nielsen.Hours.std()/sqrt(nielsen.Hours.size))).round(1)

array([8.1, 8.9])